# Assignment1 

## Matrix 구현 
1. Linear Regression 에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해 주세요 
2. LSE에서 쓰이는 Loss Function, **MSE**를 행렬로 구현해 출력해 주세요 

### Data Load 

In [1]:
import pandas as pd 
data = pd.read_csv("assignment1.csv")

In [2]:
data.head()

y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [3]:
data.shape # y:(9,1), X:(9,5)

(9, 6)

In [4]:
X = data.drop(["y"], axis=1)
y = data.y

In [5]:
# matrix 계산을 위해 numpy 형태로 바꾸어 줍니다 
X = X.to_numpy()
y = y.to_numpy()

In [6]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [7]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5], dtype=int64)

### 1. Normal Equation

In [10]:
import numpy as np
from numpy.linalg import inv 

![nn](정규방정식.PNG)

In [45]:
def estimate_beta(X, y):
    x0 = np.ones((X.shape[0],1)) 
    X = np.hstack((x0, X)) # 절편을 위한 1 덧대기
    beta_hat = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
    
    return beta_hat

In [46]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

#### 실제 값과 비교

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)

In [19]:
print(model.intercept_) # intercept
print(model.coef_) # 추정된 회귀계수 (intercept제외)

-39.24473678135658
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]


### 2. MSE

In [69]:
#     mse = np.square(np.subtract(y, y_pred)).mean()
def MSE(X, y, beta_hat):
    x0 = np.ones((X.shape[0],1))
    X = np.hstack((x0, X))   # 절편을 위한 1 덧대기
    y_pred = X.dot(beta_hat) # x*b
    e = y - y_pred           # y - yhat
    mse = (e.T.dot(e))/X.shape[0] # (y-yhat)^2의 합을 n으로 나누기
    return mse

In [72]:
MSE(X, y, estimate_beta(X, y))

1.6155977229019176

### 3.MLE

#### 바구니 안에 파란구슬과 빨간구슬이 들어있을 때, 10개를 추출하여보니 파란구슬이 2개 빨간구슬이 8개가 추출되었습니다. 
#### 이때 바구니안에는 파란구슬과 빨간구슬이 각각 몇개있는지에 대해서 최대우도추정법을 이용해 논리적으로 설명해주세요. 
- 수식은 있어도 좋고 말로 풀어쓰셔도 좋습니다
- 추출은 복원추출을 전제로 합니다
- 글자수 제한은 없습니다. 많이 쓰라는 얘기가 아니라 정말 제한이 없습니다. 너무 부담가지고 쓰지마세요.

최대우도추정법은 관찰한 사건이 있을 때 이 사건이 일어날 확률을 최대로 높이는 모수를 추정하는 것이고, 아래와 같은 흐름으로 진행됩니다.
1. 모델을 설정하고
2. 모델에서 발생한 사건의 발생 확률식을 설정하고
3. 그 확률을 최대한 높이는 모델 변수를 구합니다.
이는 어떤사건을 목격했을 때 이 사건이 일어난 것은 어쩌다 한번 일어나는 일이 아니라 평소에 많이 일어나는 일이기때문에 내가 관찰할 수 있었던 것이고,
그렇기에 발생확률을 최대로 높이는 변수를 구하는 것입니다.

문제에서 바구니안에 전체 구슬 수가 100개였다고 가정합니다.
![nn](구슬.JPG)
100 * (2/10) = 20개의 파란 구슬이 있었을 것입니다.
빨간구슬은 이와 마찬가지로 추정하면 80개가 있었을 것입니다.

참고자료:https://www.youtube.com/watch?v=sOtkPm_1GYw